/**
 * Mobile-First Compact AI CLI Dictionary & Detailed Command Help Encyclopedia
 * 1. Compact Single-Line Dictionary (< 30 cells) strictly eliminates line-wrap cursor bugs.
 * 2. Detailed Command Help Map powers the immersive floating command preview capsule.
 */

export const DETAILED_COMMAND_HELP_MAP: Record<
  string,
  { title: string; enCmd: string; desc: string; usage?: string; tip?: string }
> = {
  '/plan': {
    title: '切换规划模式',
    enCmd: '/plan',
    desc: '进入只读架构分析与任务拆解模式。AI 将先输出详细的实施方案与步骤，绝不会擅自修改任何代码文件。',
    usage: '/plan [可选任务目标]',
    tip: '在执行大型功能重构或复杂 Bug 修复前，强烈建议先用 /plan 明确步骤！',
  },
  '/goal': {
    title: '设置任务目标',
    enCmd: '/goal',
    desc: '为长时间运行的自主 Agent 设定终极目标。AI 将自动闭环执行多步任务直到达成该目标。',
    usage: '/goal <终极目标描述>',
    tip: '目标描述越清晰具体（包含验收标准），Agent 的执行质量越高。',
  },
  '/clear': {
    title: '清空会话上下文',
    enCmd: '/clear',
    desc: '彻底清空当前终端屏幕与历史会话上下文，释放所有 Token 占用，开启全新独立的任务。',
    usage: '/clear',
    tip: '当开始一个完全不相关的全新任务时，使用 /clear 可以显著提升响应速度并节省费用。',
  },
  '/compact': {
    title: '智能压缩上下文',
    enCmd: '/compact',
    desc: '提取对话历史中的核心结论、代码决策与未完成事项，压缩冗余 Token，大幅释放上下文窗口。',
    usage: '/compact',
    tip: '当上下文占用超过 70% 提示警告时，使用 /compact 可以立竿见影释放空间！',
  },
  '/context': {
    title: '上下文用量分析',
    enCmd: '/context',
    desc: '查看当前会话已使用的 Token 总量、各文件占比可视化图表与优化建议。',
    usage: '/context',
    tip: '帮助您快速发现是否有超大无用文件占用了过多上下文。',
  },
  '/agents': {
    title: '智能体协作管理',
    enCmd: '/agents',
    desc: '查看当前所有活跃的 Agent 智能体列表，并支持在不同专精子 Agent 之间快速切换。',
    usage: '/agents',
    tip: '支持并行调度研究型、代码重构型等不同角色的子智能体协同作战。',
  },
  '/model': {
    title: '切换底层大模型',
    enCmd: '/model',
    desc: '实时切换或查看当前 AI CLI 正在使用的底层推理模型（例如 Claude 3.7 Sonnet、GPT-4o 等）。',
    usage: '/model [模型名称]',
    tip: '简单任务可使用轻量小模型提速，高难度架构任务切换至旗舰大模型。',
  },
  '/diff': {
    title: 'Git 变更代码对比',
    enCmd: '/diff',
    desc: '查看工作区所有已修改文件、新增未跟踪文件的 Git 差异对比，直观展示代码增删行。',
    usage: '/diff',
    tip: '在提交代码前使用 /diff 进行全量复核，确保没有意外多改文件。',
  },
  '/review': {
    title: '全方位代码质量审查',
    enCmd: '/review',
    desc: '指示 AI 对当前分支的代码修改进行全方位的架构、安全性、异常边界与代码异味审查。',
    usage: '/review [分支名]',
    tip: '相当于自带一位资深架构师为您做代码审查 (Code Review)！',
  },
  '/undo': {
    title: '撤销上一步修改',
    enCmd: '/undo',
    desc: '一键撤销 AI 上一步对文件所做的所有代码改动，将工作区精准回滚至修改前状态。',
    usage: '/undo',
    tip: '若 AI 改动的效果不符合预期，直接敲 /undo 即可无损回退。',
  },
  '/commit': {
    title: '智能生成 Git 提交',
    enCmd: '/commit',
    desc: 'AI 自动分析当前暂存的所有代码差异，自动生成符合 Conventional Commits 规范的精准提交信息并提交。',
    usage: '/commit',
    tip: '告别手动写 Commit Message，地道标准又省心。',
  },
  '/doctor': {
    title: '环境健康诊断',
    enCmd: '/doctor',
    desc: '全面检查本地 Node.js、Python、Git、API Key 及网络连通性等开发环境依赖是否就绪。',
    usage: '/doctor',
    tip: '当遇到工具运行异常或权限报错时，第一步先跑 /doctor 诊断。',
  },
  '/mcp': {
    title: 'MCP 插件服务管理',
    enCmd: '/mcp',
    desc: '配置、连接或管理基于 Model Context Protocol (MCP) 标准的外部工具服务与数据源插件。',
    usage: '/mcp [list|add|remove]',
    tip: '扩展 AI 的能力边界，让 AI 直接操作数据库、GitHub 或浏览器！',
  },
  '/permissions': {
    title: '安全执行权限管理',
    enCmd: '/permissions',
    desc: '查看或配置允许 AI 自动执行的 Shell 终端指令与文件修改安全白名单。',
    usage: '/permissions',
    tip: '开启自动授权可以减少频繁确认弹框，提升自动化开发效率。',
  },
  '/add': {
    title: '添加文件到上下文',
    enCmd: '/add',
    desc: '将指定的单个文件、通配符或目录完整加载到 AI 对话上下文中供参考与修改。',
    usage: '/add <文件路径/通配符>',
    tip: '精准添加相关文件能让 AI 更快定位逻辑并减少 Token 浪费。',
  },
  '/drop': {
    title: '从上下文中移除文件',
    enCmd: '/drop',
    desc: '从当前 AI 编码会话中移出指定文件，释放上下文空间。',
    usage: '/drop <文件路径>',
    tip: '完成某模块开发后，及时 /drop 掉已无关的文件。',
  },
  '/help': {
    title: '查看帮助与命令列表',
    enCmd: '/help',
    desc: '列出当前开发工具支持的所有可用斜杠命令、键盘快捷键与使用说明。',
    usage: '/help',
    tip: '随时输入 /help 探索更多高级功能。',
  },
};

/** Reverse Mapping from Chinese Commands to English Commands */
export const CHINESE_SLASH_CMD_MAP: Record<string, string> = {
  '/规划': '/plan',
  '/目标': '/goal',
  '/智能体': '/agents',
  '/副对话': '/side',
  '/复制': '/copy',
  '/导出': '/export',
  '/纯文本': '/raw',
  '/对比': '/diff',
  '/技能': '/skills',
  '/模型': '/model',
  '/帮助': '/help',
  '/清空': '/clear',
  '/重置': '/reset',
  '/测试': '/test',
  '/状态': '/status',
  '/压缩': '/compact',
  '/配置': '/config',
  '/插件': '/mcp',
  '/权限': '/permissions',
  '/诊断': '/doctor',
  '/分享': '/share',
  '/撤销': '/undo',
  '/提交': '/commit',
  '/初始化': '/init',
  '/退出': '/exit',
  '/上下文': '/context',
  '/恢复': '/resume',
  '/派生': '/fork',
  '/回滚': '/rewind',
  '/快照': '/checkpoint',
  '/追问': '/btw',
  '/费用': '/cost',
  '/反馈': '/bug',
  '/登录': '/login',
  '/登出': '/logout',
  '/合并': '/pr',
  '/审查': '/review',
  '/安全': '/security',
  '/终端': '/terminal',
  '/添加': '/add',
  '/移除': '/drop',
  '/清单': '/ls',
  '/拓扑': '/map',
  '/代码': '/code',
  '/提问': '/ask',
  '/架构': '/architect',
  '/抓取': '/web',
  '/只读': '/read-only',
  '/语音': '/voice',
  '/检查': '/lint',
  '/编辑': '/edit',
  '/连接': '/connect',
  '/调试': '/debug',
  '/重命名': '/rename',
  '/摘要': '/summarize',
  '/准则': '/rules',
  '/执行': '/run',
};

/**
 * Ultra-Compact Dictionary Strictly Under 30 Physical Cells
 * Ensures zero line-wrap on mobile portrait screens (360px~420px width).
 */
export const DEV_TOOL_EXACT_DICT: Record<string, string> = {
  // === 1. OpenAI Codex CLI (Compact Single-Line) ===
  '/plan': '/规划 (plan) 规划模式',
  '/goal': '/目标 (goal) 任务目标',
  '/agents': '/智能体 (agents) 切换智能体',
  '/side': '/副对话 (side) 临时分支',
  '/copy': '/复制 (copy) 复制回复',
  '/export': '/导出 (export) 导出文档',
  '/raw': '/纯文本 (raw) 纯文本模式',
  '/diff': '/对比 (diff) 代码对比',
  '/skills': '/技能 (skills) 调度技能',
  '/model': '/模型 (model) 切换模型',
  '/help': '/帮助 (help) 命令列表',
  '/clear': '/清空 (clear) 清空重置',
  '/test': '/测试 (test) 运行测试',
  '/status': '/状态 (status) 系统状态',
  '/compact': '/压缩 (compact) 压缩空间',
  '/config': '/配置 (config) 全局配置',
  '/mcp': '/插件 (mcp) 插件服务',
  '/permissions': '/权限 (permissions) 权限管理',
  '/doctor': '/诊断 (doctor) 环境诊断',
  '/reset': '/重置 (reset) 重置会话',
  '/share': '/分享 (share) 分享链接',
  '/undo': '/撤销 (undo) 撤销修改',
  '/commit': '/提交 (commit) 智能提交',
  '/init': '/初始化 (init) 规范配置',
  '/exit': '/退出 (exit) 退出会话',
  '/quit': '/退出 (quit) 退出程序',

  // === 2. Anthropic Claude Code CLI (Compact) ===
  '/context': '/上下文 (context) Token分析',
  '/resume': '/恢复 (resume) 恢复会话',
  '/fork': '/派生 (fork) 派生副本',
  '/rewind': '/回滚 (rewind) 回退检查点',
  '/checkpoint': '/快照 (checkpoint) 快照管理',
  '/btw': '/追问 (btw) 快速提问',
  '/cost': '/费用 (cost) 账单用量',
  '/bug': '/反馈 (bug) 提交反馈',
  '/login': '/登录 (login) 账号登录',
  '/logout': '/登出 (logout) 退出登录',
  '/pr': '/合并 (pr) 审查 PR',
  '/review': '/审查 (review) 代码审查',
  '/security': '/安全 (security) 安全扫描',
  '/terminal': '/终端 (terminal) 终端切换',

  // === 3. Aider AI Pair Programmer (Compact) ===
  '/add': '/添加 (add) 加载文件',
  '/drop': '/移除 (drop) 移除文件',
  '/ls': '/清单 (ls) 文件清单',
  '/map': '/拓扑 (map) 依赖拓扑',
  '/code': '/代码 (code) 编写模式',
  '/ask': '/提问 (ask) 只读答疑',
  '/architect': '/架构 (architect) 架构模式',
  '/chat-mode': '/模式 (chat-mode) 切换模式',
  '/git': '/原生Git (git) Git 指令',
  '/run': '/执行 (run) 执行命令',
  '/tokens': '/统计 (tokens) Token统计',
  '/web': '/抓取 (web) 抓取网页',
  '/read-only': '/只读 (read-only) 只读文件',
  '/voice': '/语音 (voice) 语音交互',
  '/lint': '/检查 (lint) 规范检查',

  // === 4. Cursor & OpenCode & Hermes (Compact) ===
  '/edit': '/编辑 (edit) 外部编辑',
  '/connect': '/连接 (connect) 模型连接',
  '/debug': '/调试 (debug) 根因调试',
  '/rename': '/重命名 (rename) 重命名会话',
  '/summarize': '/摘要 (summarize) 提取摘要',
  '/rules': '/准则 (rules) AI 准则',
  '/shell': '/终端沙箱 (shell) 沙箱指令',
  '/docs': '/文档 (docs) 检索文档',
  '/composer': '/多文件 (composer) 协同编辑',
  '/editor': '/编辑器 (editor) 系统编辑器',
  '/session': '/会话 (session) 历史会话',
  '/switch': '/切换 (switch) 快速切换',
  '/attach': '/接入 (attach) 接入任务',
  '/history': '/历史 (history) 历史执行',
  '/prune': '/清理 (prune) 清理缓存',

  // === 5. Interactive Menus & CLI Questions ===
  '? Project name:': '? 项目名称：',
  '? Select a framework:': '? 选择框架：',
  '? Select a variant:': '? 选择语言变体：',
  '? Use TypeScript?': '? 是否使用 TypeScript？',
  '? Use ESLint to lint your code?': '? 是否启用 ESLint？',
  '? Use Tailwind CSS for styling?': '? 是否启用 Tailwind CSS？',
  '? Would you like to use App Router? (recommended)': '? 使用 App Router？(推荐)',
  '? Would you like to use Turbopack for next dev?': '? 启用 Turbopack 编译器？',
  '? Would you like to customize the default import alias (@/*)?': '? 自定义别名 (@/*)？',
  '? What is your project named?': '? 您的项目名称：',
  '? Initialize a new git repository?': '? 初始化 Git 仓库？',
  '? Select package manager:': '? 选择包管理器：',
  'Vanilla': '原生 JavaScript/TypeScript',
  'Vue': 'Vue.js (渐进式框架)',
  'React': 'React (声明式 UI 库)',
  'Preact': 'Preact (轻量级 3kB 方案)',
  'Lit': 'Lit (Web Components 库)',
  'Svelte': 'Svelte (增强型 Web 框架)',
  'Solid': 'Solid.js (高响应式 UI 库)',
  'Qwik': 'Qwik (可恢复极速框架)',
  'TypeScript': 'TypeScript (类型安全)',
  'JavaScript': 'JavaScript (原生脚本)',
  'dev server running at:': '开发服务器已启动于：',
  'Local:': '本地访问地址：',
  'Network:': '局域网访问地址：',
  'Network: use --host to expose': '局域网访问：添加 --host 向局域网暴露',
  'press h + enter to show help': '按 h + 回车查看快捷键',
  'press q to quit': '按 q 退出服务',
  'press r to restart the server': '按 r 重启服务器',
  'press u to show server url': '按 u 显示访问地址',
  'press o to open in browser': '按 o 在浏览器中打开',
  'press c to clear console': '按 c 清空控制台',

  // === 6. Git & Linux System ===
  'On branch main': '位于分支 main',
  'On branch master': '位于分支 master',
  'Your branch is up to date with': '分支已与远程保持最新',
  'Your branch is ahead of': '本地分支领先于远程',
  'Your branch is behind': '本地分支落后于远程',
  'Changes not staged for commit:': '未暂存的更改：',
  'Changes to be committed:': '待提交的暂存：',
  'Untracked files:': '未跟踪的新文件：',
  'nothing to commit, working tree clean': '工作区干净',
  'Permission denied': '权限被拒绝 (请检查权限或 sudo)',
  'No such file or directory': '没有该文件或目录 (检查路径)',
  'Command not found': '未找到该命令 (请 apt install)',
  'command not found': '未找到该命令 (请 apt install)',
  'Connection refused': '连接被拒绝 (服务未启动或防火墙阻断)',
  'Connection timed out': '连接超时 (网络不可达)',
  'Address already in use': '端口已被占用 (请关闭冲突进程)',
};

/** Dynamic Template RegEx Replacers */
export const DEV_TOOL_TEMPLATES: Array<{ pattern: RegExp; replace: (...args: string[]) => string }> = [
  {
    pattern: /^added\s+(\d+)\s+packages?(?:\s+and\s+audited\s+(\d+)\s+packages?)?\s+in\s+([\d.]+)(m?s)/i,
    replace: (_, added, audited, time, unit) =>
      `安装了 ${added} 个包${audited ? ` (审计 ${audited} 个包)` : ''}，耗时 ${time}${unit}`,
  },
  {
    pattern: /^ready\s+in\s+([\d.]+)\s*(m?s)/i,
    replace: (_, time, unit) => `启动就绪，耗时 ${time} ${unit}`,
  },
  {
    pattern: /^found\s+(\d+)\s+vulnerabilit(?:y|ies)(?:\s*\((.*?)\))?/i,
    replace: (_, count, details) =>
      `发现 ${count} 个安全漏洞${details ? ` (${details})` : ''}`,
  },
  {
    pattern: /^Context\s+(\d+)%\s+used/i,
    replace: (_, percent) => `上下文已使用 ${percent}%`,
  },
  {
    pattern: /^Tokens:\s*([\d,]+)\s*\/\s*([\d,]+)\s+used\s*\(([\d.]+)%\)/i,
    replace: (_, used, total, pct) => `Token：${used} / ${total} (${pct}%)`,
  },
];
