/**
 * Comprehensive Developer IT & CLI Terminology Dictionary
 * Covers Claude Code, OpenAI Codex, Cursor, Aider, OpenCode, Hermes, Pi, Vite, Next.js, Vue, React, Bun, Rust Cargo, Python, Docker, Git, Linux.
 */

export const DEV_TOOL_EXACT_DICT: Record<string, string> = {
  // === 1. Claude Code CLI All Slash Commands ===
  '/clear': '/clear 清空对话历史并重置当前上下文 (开启新任务)',
  '/compact': '/compact 智能压缩对话历史以大幅释放上下文空间',
  '/context': '/context 查看当前上下文 Token 占用可视化图表与优化建议',
  '/resume': '/resume 恢复并继续之前的交互式会话',
  '/fork': '/fork 派生当前会话创建独立分支副本',
  '/init': '/init 在当前工程中自动分析并生成 CLAUDE.md 项目规范',
  '/plan': '/plan 切换到规划模式 (Plan Mode，仅分析不修改文件)',
  '/status': '/status 查看当前活跃工具、上下文文件与系统状态',
  '/diff': '/diff 查看 Git 代码变更对比 (含未跟踪的新增文件)',
  '/model': '/model 切换或查看当前底层大模型',
  '/mcp': '/mcp 配置、管理或连接 MCP (Model Context Protocol) 插件服务',
  '/permissions': '/permissions 管理工具调用与命令执行的安全授权白名单',
  '/cost': '/cost 查看当前会话累计消耗的 Token 用量与账单成本',
  '/config': '/config 查看或修改当前工具链全局配置项',
  '/doctor': '/doctor 运行系统与运行环境健康诊断检查',
  '/bug': '/bug 提交问题反馈与运行日志',
  '/login': '/login 登录并验证账号身份认证凭据',
  '/logout': '/logout 退出登录并清除本地授权凭据',
  '/pr': '/pr 创建或审查 GitHub Pull Request 代码合并请求',
  '/review': '/review 对当前 Git 分支代码变更进行全方位质量审查',
  '/security': '/security 扫描项目依赖与代码安全漏洞',
  '/terminal': '/terminal 打开或切换内嵌终端执行上下文',

  // === 2. Aider CLI All Slash Commands ===
  '/add': '/add 将指定文件或目录添加到 AI 编码上下文中',
  '/drop': '/drop 从 AI 编码上下文中移除指定文件',
  '/ls': '/ls 列出当前会话已加载的所有文件清单',
  '/map': '/map 打印当前代码仓库的完整依赖拓扑结构图',
  '/code': '/code 切换为代码编写模式 (默认自动应用代码修改)',
  '/ask': '/ask 切换为只读答疑模式 (只回答问题，不修改代码)',
  '/architect': '/architect 切换为系统架构模式 (先给出设计方案再实施)',
  '/help': '/help 查看帮助与可用命令详细列表',
  '/commit': '/commit 智能生成精准提交信息并执行 Git 提交',
  '/undo': '/undo 撤销上一步 AI 所做的代码修改并回滚文件',
  '/git': '/git 在会话内直接执行 Git 原生命令',
  '/run': '/run 在会话内直接执行 Shell 终端命令',
  '/tokens': '/tokens 查看当前上下文 Token 消耗明细与统计',
  '/web': '/web 抓取并解析网页内容作为上下文参考',
  '/read-only': '/read-only 将指定文件设置为只读上下文 (AI 不得修改)',
  '/voice': '/voice 开启语音输入转文字交互',

  // === 3. OpenAI Codex CLI All Slash Commands ===
  '/goal': '/goal 设置或查看长时间运行自主任务的终极目标',
  '/agents': '/agents 查看并在所有活跃的 Agent 智能体间切换',
  '/side': '/side 在临时沙箱分支中开启独立副对话',
  '/copy': '/copy 复制最新回复内容、代码块或引用片段',
  '/export': '/export 将完整对话记录导出为标准 Markdown 文档',
  '/raw': '/raw 切换便于复制的原生纯文本回滚模式',
  '/skills': '/skills 列出可用技能库或指示 Codex 调度指定技能',
  '/test': '/test 运行当前工程的自动化测试套件',
  '/reset': '/reset 重置会话与运行环境状态',
  '/share': '/share 生成当前会话的在线分享链接',

  // === 4. Cursor & OpenCode All Slash Commands ===
  '/edit': '/edit 打开外部编辑器进行长文本编辑与微调',
  '/connect': '/connect 连接或配置自定义 AI 模型提供商与 API 密钥',
  '/debug': '/debug 自动捕获报错堆栈并进行代码根因调试分析',
  '/rename': '/rename 重命名当前会话标题',
  '/summarize': '/summarize 提取当前对话关键摘要并归档',
  '/rules': '/rules 查看或编辑当前项目的 AI 行为准则 (.cursorrules)',
  '/shell': '/shell 在沙箱环境中执行终端指令',
  '/exit': '/exit 退出并关闭当前交互式会话',
  '/quit': '/quit 退出当前程序',

  // === 5. Modern Frontend & Scaffolding (Create-Vite, Next, Vue, React, Bun) ===
  '? Project name:': '? 项目名称：',
  '? Select a framework:': '? 请选择前端框架：',
  '? Select a variant:': '? 请选择开发语言变体 (TypeScript / JavaScript)：',
  '? Use TypeScript?': '? 是否使用 TypeScript？',
  '? Use ESLint to lint your code?': '? 是否启用 ESLint 代码规范检查？',
  '? Use Tailwind CSS for styling?': '? 是否启用 Tailwind CSS 样式库？',
  '? Would you like to use App Router? (recommended)': '? 是否使用 App Router 现代应用路由架构？(推荐)',
  '? Would you like to use Turbopack for next dev?': '? 是否启用 Turbopack 极速开发编译器？',
  '? Would you like to customize the default import alias (@/*)?': '? 是否自定义模块导入路径别名 (@/*)？',
  '? What is your project named?': '? 您的项目名称是什么？',
  '? Initialize a new git repository?': '? 是否自动初始化 Git 代码仓库？',
  '? Select package manager:': '? 请选择依赖包管理器 (pnpm / npm / yarn / bun)：',
  'Select a framework:': '选择前端项目框架：',
  'Select a variant:': '选择开发语言变体 (TypeScript / JavaScript)：',
  'Vanilla': '原生 JavaScript/TypeScript',
  'Vue': 'Vue.js (渐进式 JavaScript 框架)',
  'React': 'React (构建用户界面的声明式库)',
  'Preact': 'Preact (轻量级 3kB React 替代方案)',
  'Lit': 'Lit (轻量级 Web Components 库)',
  'Svelte': 'Svelte (控制论增强型 Web 应用)',
  'Solid': 'Solid.js (简单高响应式 UI 库)',
  'Qwik': 'Qwik (可恢复极速加载框架)',
  'Others': '其他选项',
  'TypeScript': 'TypeScript (类型安全)',
  'JavaScript': 'JavaScript (原生脚本)',
  'Customize with create-vue': '使用 create-vue 深度定制',
  'Nuxt': 'Nuxt.js (全栈 Vue 框架)',
  'Next.js': 'Next.js (企业级全栈 React 框架)',
  'Install dependencies?': '是否立即安装依赖包？',
  'dev server running at:': '开发服务器已启动于：',
  'Local:': '本地访问地址：',
  'Network:': '局域网访问地址：',
  'Network: use --host to expose': '局域网访问：添加 --host 参数以向局域网暴露服务',
  'press h + enter to show help': '按 h + 回车查看可用快捷键菜单',
  'press q to quit': '按 q 退出服务',
  'press r to restart the server': '按 r 重新启动开发服务器',
  'press u to show server url': '按 u 显示服务器访问地址',
  'press o to open in browser': '按 o 在默认浏览器中打开',
  'press c to clear console': '按 c 清空控制台屏幕',

  // === 6. Git Version Control System ===
  'On branch main': '位于分支 main',
  'On branch master': '位于分支 master',
  'Your branch is up to date with': '您的分支已与远程分支保持最新',
  'Your branch is ahead of': '您的分支领先于远程分支',
  'Your branch is behind': '您的分支落后于远程分支',
  "Your branch and 'origin/main' have diverged": "本地分支与远程分支出现分叉 (存在不同的提交)",
  'Changes not staged for commit:': '已修改但尚未暂存的更改 (使用 git add 暂存)：',
  'Changes to be committed:': '待提交的暂存更改 (使用 git commit 提交)：',
  'Untracked files:': '未跟踪的新文件 (使用 git add 纳入版本控制)：',
  'nothing to commit, working tree clean': '无待提交的更改，工作区干净',
  'nothing added to commit but untracked files present': '未暂存任何提交内容，但工作区存在未跟踪文件',
  'fatal: not a git repository (or any of the parent directories): .git': '致命错误：当前目录 (及父目录) 不是 Git 代码仓库',
  'Already up to date.': '已经是最新版本。',
  'Everything up-to-date': '所有内容均已是最新状态',
  'Auto-merging': '正在自动合并文件',
  'CONFLICT (content): Merge conflict in': '冲突 (内容)：文件合并发生冲突：',
  'Automatic merge failed; fix conflicts and then commit the result.': '自动合并失败；请先手动解决冲突，然后再提交结果。',
  'Stage this hunk [y,n,q,a,d,s,e,?]?': '暂存当前代码块 [y(是),n(否),q(退出),a(全部),d(跳过),s(拆分),e(编辑),?(帮助)]?',
  'rebase in progress; onto': '正在进行变基操作 (Rebase)；目标提交为',
  'all conflicts fixed: run "git rebase --continue"': '所有冲突已解决：请执行 "git rebase --continue" 继续',
  'git push --set-upstream origin': '请使用 git push --set-upstream origin 建立上游关联',

  // === 7. Rust Compiler & Toolchain ===
  'borrow of moved value': '借用了已被移动所有权的值 (所有权冲突)',
  'cannot borrow as mutable more than once at a time': '同一时间不能对同一变量进行多次可变借用',
  'lifetime may not live long enough': '生命周期可能不够长 (变量存活期超出预期)',
  'consider cloning the value if the performance cost is acceptable': '建议：若性能开销可接受，可考虑使用 .clone() 复制该值',
  'consider borrowing here': '建议：在此处使用引用 (&) 进行借用',
  'cargo clippy --fix': '自动应用 Clippy 建议的代码优化补丁',

  // === 8. Python, Docker, Linux Core ===
  'Application startup complete.': '应用程序启动完成，已进入就绪监听状态',
  'Waiting for application shutdown.': '正在等待应用程序安全关闭并释放连接池...',
  'RuntimeError: Event loop is closed': '运行时错误：AsyncIO 异步事件循环已提前关闭',
  'Permission denied': '权限被拒绝 (请检查文件读写执行权限或使用 sudo/su)',
  'No such file or directory': '没有该文件或目录 (请检查路径拼写)',
  'Command not found': '未找到该命令 (请检查拼写或使用 apt install 安装)',
  'command not found': '未找到该命令 (请检查拼写或使用 apt install 安装)',
  'Connection refused': '连接被拒绝 (目标服务未启动或端口被防火墙拦截)',
  'Connection timed out': '连接超时 (网络不可达或对端无响应)',
  'Address already in use': '端口已被占用 (请先关闭冲突进程)',
  'Too many open files': '打开的文件句柄数已达系统上限 (ulimit)',
  'Name or service not known': '域名解析失败或 DNS 服务不可达',
  'Temporary failure in name resolution': 'DNS 域名解析暂时性失败 (请检查 /etc/resolv.conf)',
  'No route to host': '无通往目标主机的网络路由 (对端离线或防火墙阻断)',
};

/** Dynamic Template RegEx Replacers */
export const DEV_TOOL_TEMPLATES: Array<{ pattern: RegExp; replace: (...args: string[]) => string }> = [
  {
    pattern: /^added\s+(\d+)\s+packages?(?:\s+and\s+audited\s+(\d+)\s+packages?)?\s+in\s+([\d.]+)(m?s)/i,
    replace: (_, added, audited, time, unit) =>
      `成功安装了 ${added} 个软件包${audited ? ` (并审计了 ${audited} 个包)` : ''}，耗时 ${time}${unit}`,
  },
  {
    pattern: /^ready\s+in\s+([\d.]+)\s*(m?s)/i,
    replace: (_, time, unit) => `启动就绪，耗时 ${time} ${unit}`,
  },
  {
    pattern: /^found\s+(\d+)\s+vulnerabilit(?:y|ies)(?:\s*\((.*?)\))?/i,
    replace: (_, count, details) =>
      `发现 ${count} 个安全漏洞${details ? ` (${details})` : ''}`,
  },
  {
    pattern: /^Context\s+(\d+)%\s+used/i,
    replace: (_, percent) => `上下文已使用 ${percent}%`,
  },
  {
    pattern: /^Tokens:\s*([\d,]+)\s*\/\s*([\d,]+)\s+used\s*\(([\d.]+)%\)/i,
    replace: (_, used, total, pct) => `Token 用量：${used} / ${total} 已使用 (${pct}%)`,
  },
  {
    pattern: /^Building for production\.{3}/i,
    replace: () => '正在进行生产环境全量打包编译...',
  },
  {
    pattern: /^HMR update\s+(.+)$/i,
    replace: (_, file) => `模块热替换 (HMR)：已更新 ${file}`,
  },
];
